The user should be able to order any package
KitechRW/Kitech_backend pull request #10
Opened 2021-01-18 12:34 UTC by Emile-Nsengimana

#### what does this PR do?
 - allows client to order any package
#### Description of task to be completed
- create an API endpoint that allows client to order any package
- save order info in database(mongodb)
#### How should this be manually tested
- Clone the project

      git clone https://github.com/KitechRW/Kitech_backend.git

- Open the project using your favorite IDE
- Change the branch

       git checkout ft-order-package

- Run the app
``` yarn run start:dev```
- Request body
```
{
      "id": UUID,
      "userId": UUID",
      "name": String,
      "fullname": String,
      "email": String,
      "phone": String,
      "serviceId": UUID,
      "serviceName": String,
      "package": String,
      "price":  Number,
      "status": options["pending", "approved", "canceled"],
      "paid": Boolean,
      "delivered": Boolean,
      "comment":  String
}
```

- Expected response
```
{
    "message": "package ordered successfully",
    "data": {
        "serviceId": UUID,
        "serviceName": String,
        "package": String,
        "price": Number,
        "status": options["pending", "approved", "canceled"],
        "paid": Boolean,
        "delivered": Boolean
    }
}
```
#### Any background context you want to provide
- N/A
#### What are the relevant trello story link
[The user should be able to order any package](https://trello.com/c/EHMHSlpa)
#### Screenshots (if appropriate)
 - N/A
#### Questions:
- N/A

2021-01-25 07:48 UTC, truestbyheart requested changes
Please can you go through the feedback and the question so I can get a clear picture of wht ur trying to achieve

2021-01-25 07:48 UTC, truestbyheart commented on package.json
> +    "bcryptjs": "^2.4.3",
why are  two bcrypt packages? @Emile-Nsengimana

2021-01-25 07:48 UTC, truestbyheart commented on src/modules/order/order.middleware.js
> +  static async orderValidator(req, res, next) {
we need a single middleware for performing joi validation

2021-01-25 07:48 UTC, truestbyheart commented on src/modules/order/order.test.js
> +    id: 'c940eed7-38dd-4789-843c-f4fe52c67067',
what is the difference between `id` and `serviceId`

2021-01-25 07:48 UTC, truestbyheart commented on src/modules/index.js
> +const { verifyToken, userLoginValidate } = authVerification;
is this being used

2021-01-25 07:48 UTC, truestbyheart commented on src/modules/index.js
> +const { verifyToken, userLoginValidate } = authVerification;
Please remove all unused code

2021-01-25 07:48 UTC, truestbyheart commented on src/modules/order/order.controller.js
> +      const { phone, _id: userId, fullname, email } = req.userData;
where are you generating this information

2021-01-25 07:48 UTC, truestbyheart commented on src/database/model/order.model.js
> +  email: {
why is name requred and not Id, the most unique thing you can count on is email but I wonder we are requiring the name instead....can you explain @Emile-Nsengimana

2021-01-25 07:54 UTC, Emile-Nsengimana commented on src/modules/index.js
> +const { verifyToken, userLoginValidate } = authVerification;
sure

2021-01-25 07:55 UTC, Emile-Nsengimana commented on src/modules/order/order.controller.js
> +      const { phone, _id: userId, fullname, email } = req.userData;
this is the information of the user who is making the order and it is being extracted from the user token

2021-01-25 08:05 UTC, Emile-Nsengimana commented on package.json
> +    "bcryptjs": "^2.4.3",
my fault didn't notice while rebasing, I think login & signup features used different bcrypt

2021-01-25 08:06 UTC, Emile-Nsengimana commented on src/modules/order/order.middleware.js
> +  static async orderValidator(req, res, next) {
for all middle-wares or generic ones?

2021-01-25 08:07 UTC, Emile-Nsengimana commented on src/modules/order/order.test.js
> +    id: 'c940eed7-38dd-4789-843c-f4fe52c67067',
id is the order id(which I don't need to provide) while serviceId is the package/service id

2021-01-25 08:09 UTC, Emile-Nsengimana commented on src/database/model/order.model.js
> +  email: {
I presumed the order need to have a name and email will always be available as it is gotten from the token because user need to be authenticated to be able to order any package

But I will make email required in the model as well

2021-01-25 13:35 UTC, harerakalex reviewed
Welldone @Emile-Nsengimana, everything looks nice to me apart from feedback @truestbyheart left on this PR.

2021-01-25 20:53 UTC, luc-tuyishime commented on package.json
> +    "bcryptjs": "^2.4.3",
Have you tried to uninstall that package ?

2021-01-25 20:53 UTC, luc-tuyishime commented on src/modules/index.js
>  indexRouter.use('/seed', loginRouter);
Can you explain the meaning of seed here ?

2021-01-25 20:53 UTC, luc-tuyishime commented on src/modules/order/order.middleware.js
> +  static async orderValidator(req, res, next) {
We need one Middleware but different schemas, that way code becomes more clean.

2021-01-25 20:54 UTC, luc-tuyishime commented
Can you add a screenshot in the PR description?

2021-01-25 20:57 UTC, Emile-Nsengimana commented on src/modules/index.js
>  indexRouter.use('/seed', loginRouter);
This is a different feature maybe @fabriceumuhire  can help

2021-01-28 13:43 UTC, Emile-Nsengimana commented on package.json
> +    "bcryptjs": "^2.4.3",
Yes I tried and it caused problems

2021-01-28 13:44 UTC, Emile-Nsengimana commented on src/modules/order/order.middleware.js
> +  static async orderValidator(req, res, next) {
done

2021-01-29 08:46 UTC, luc-tuyishime approved these changes

2021-01-29 08:46 UTC, merged