Manager should be able to create services
KitechRW/Kitech_backend pull request #3
Opened 2021-01-06 23:01 UTC by erickyvand

- Manager should be able to create services

2021-01-14 06:43 UTC, fridolinho commented
![](https://github.trello.services/images/mini-trello-icon.png) [The manager should be able to register services](https://trello.com/c/xtcD1E9d/19-the-manager-should-be-able-to-register-services)

2021-01-18 15:04 UTC, raymond42 commented on src/modules/services/service.controller.js
> +      descriptions: req.body.descriptions,
can we destructure every `req.body` and we call it's corresponding? it can be much better and clean to read

2021-01-18 15:13 UTC, raymond42 commented on src/modules/mail/mail.controller.js
> +        to: 'fridolinho@gmail.com',
I know this may not be concerning with your work, but can we have these emails exposed here in `.env` instead?

2021-01-18 15:16 UTC, erickyvand commented on src/modules/mail/mail.controller.js
> +        to: 'fridolinho@gmail.com',
This one came to my work because I did a linting fix

2021-01-18 15:18 UTC, raymond42 requested changes
Nice work @erickyvand. For me it's just a few comments left, you can attend on them. Otherwise, it's a nice work here

2021-01-22 08:23 UTC, merged