User should be able to login
KitechRW/Kitech_backend pull request #6
Opened 2021-01-09 17:09 UTC by fabriceumuhire

### What does this PR do?
- Users can login to the application with their respective credentials
### How to test this PR?
- Checkout to this branch `ft-signin-user`
- Run the development environment
- Use POSTMAN to `POST` request using this url: `https://localhost:3000/api/v1/login`
### Any background
- User model to be finalized and start testing
- Mocha tests are being developed
### Screenshots

2021-01-13 06:07 UTC, fridolinho requested changes
Fix the tests with suggested changes apply changes suggested on slack as well, everythingelse look Good to me

2021-01-13 06:07 UTC, fridolinho commented on package.json
> +    "test": "nyc mocha --require @babel/register 'src/**/**test.js' --timeout 100000 --exit",
"test": "NODE_ENV=test nyc mocha --require @babel/register 'src/**/**test.js' --timeout 100000 --exit",

2021-01-13 09:35 UTC, harerakalex requested changes

2021-01-13 09:35 UTC, harerakalex commented on src/modules/user/login.controller.js
> +const login = async (_req, res) =>{
Kindly document this function using `JSDoc`, and document each and every function that needs it.

2021-01-13 18:13 UTC, truestbyheart requested changes
Good work, just a few comments, and feedback can you please through them. if you require further explanation please ping me on slack

2021-01-13 18:13 UTC, truestbyheart commented on src/modules/user/login.controller.js
> +const login = async (_req, res) =>{
Please remove the underscore from the req, this is only added if the parameter is not used so as to overcome the unused var eslint error

2021-01-13 18:13 UTC, truestbyheart commented on src/modules/user/login.controller.js
> +        if(!user) return res.status(UNAUTHORIZED).json({
Please remove this implementation we are not supposed to tell the client if the email or password is wrong, we only inform the client that the information provided is incorrect  e.g email/password is incorrect

2021-01-13 18:13 UTC, truestbyheart commented on src/modules/user/login.test.js
> +        res.should.have.status(200);
Please add more context to this test check if the object returned is correct or not instead of just testing for the reponse

2021-01-13 18:13 UTC, truestbyheart commented on src/modules/user/tokenAuth.js
> +const verifyToken = (req, res, next) => {
This is supposed to be a shared middleware that can be used by everyone please create a Shared folder inside the `modules` folder and within it add `middleware` folder and create the `auth.middleware.js`

2021-01-13 18:13 UTC, truestbyheart commented on src/server.js
> +  const mongod = new MongoMemoryServer();
can you please elaborate the use of this

2021-01-14 06:41 UTC, fabriceumuhire commented on src/modules/user/login.controller.js
> +const login = async (_req, res) =>{
This has been resolved, thanks for the comment.

2021-01-14 06:42 UTC, fridolinho commented
![](https://github.trello.services/images/mini-trello-icon.png) [User should be to login to the system](https://trello.com/c/kuhkt1gQ/16-user-should-be-to-login-to-the-system)

2021-01-14 06:52 UTC, fabriceumuhire commented on src/server.js
> +  const mongod = new MongoMemoryServer();
This has been solved as well. Thanks for noticing this.

2021-01-14 07:08 UTC, fabriceumuhire commented on src/modules/user/tokenAuth.js
> +const verifyToken = (req, res, next) => {
Great advise, I have implemented as requested.

2021-01-14 17:26 UTC, fabriceumuhire commented on src/modules/user/login.controller.js
> +const login = async (_req, res) =>{
@harerakalex Please check and let me know if I have missed anything.

2021-01-14 18:02 UTC, fabriceumuhire commented on src/modules/user/login.test.js
> +        res.should.have.status(200);
I have add some more context for this.

2021-01-20 07:49 UTC, fridolinho approved these changes

2021-01-20 07:49 UTC, merged