Chore: User Should Be Able To Create An Account
KitechRW/Kitech_backend pull request #7
Opened 2021-01-09 21:01 UTC by key-joshua

## WHAT DOES THIS PR DO?

- I have created an endpoint to create a user account.
- I have to create a user model to store a user account.

## DESCRIPTION OF TASK TO BE COMPLETED?

- During the completion of this work I have created an endpoint that will be used to create a user account from the application
  and also I have to create a model that will store a created user account.

## HOW SHOULD THIS BE MANUALLY TESTED?

####  The way this will be tested:

- should clone this repository with ```git clone https://github.com/KitechRW/Kitech_backend.git```
- After cloning, should switch into a ch-user-create-account branch with ```git checkout ch-user-create-account```

- After diving into a branch, should run the ```npm cache clean --force``` &```npm install``` by installing required libraries.
- After installing the required libraries - should also set up a .env file by referring to the .env.example with DB connection.

- After - should run ```npm run start:dev``` by starting the server.
- Ready to test an endpoint into postman with this API ```localhost:3000/api/v1/create-user-account```.

#### When a request runs correctly we expect the response below:
-------------------------------------------------------------------------------

```
{
    "status": 200,
    "message": "User account created successfully",
    "data": {
        "fullname": "FirstNname LastName",
        "email": "youremail@gmail.com",
        "phone": "+25070000000",
        "role": [
            "visitor",
            "client"
        ],
        "password": "qwerty@123",
        "confirmPassword": "qwerty@123",
        "subscription": [
            {
                "serviceId": "kdjnqkdnjkq",
                "startDate": "2020-05-20",
                "expirationDate": "2020-05-25",
                "status": [
                    "expiring"
                ]
            }
        ],

        "createdAt": "2021-01-09T23:07:09.493Z",
        "updatedAt": "2021-01-09T23:07:09.493Z"
    }
}
```

## ANY BACKGROUND CONTEXT YOU  WANT TO PROVIDE?

- The context is all about Node.js and Express with required libraries.

## WHAT ARE THE RELEVANT TRELLO TRACKER STORIES?
- [Chore: Create A User Account](https://trello.com/c/rYY47tdU/14-the-user-should-be-able-to-create-an-account)

#### SCREENSHOTS (IF APPROPRIATE)

#### For Postman
![Create User Account API](https://user-images.githubusercontent.com/38179232/104108387-ed1f7580-52cc-11eb-8058-431b14b2676d.PNG)

#### For Test
![Create User Account Test](https://user-images.githubusercontent.com/38179232/104108385-e7c22b00-52cc-11eb-8788-9d9fccacc9b7.PNG)

2021-01-12 04:49 UTC, fridolinho reviewed
Hello @key-joshua Good job so far, however I didn't see the successful test case.

2021-01-12 04:49 UTC, fridolinho commented on src/database/model/user.model.js
> +      'fixed phone number address is required, please try again',
Update the error message "to email is required, ..............

2021-01-12 04:49 UTC, fridolinho commented on src/modules/account/account.controller.js
> +                message: 'Invalid role, role should be array [visitor, client, manager, admin]',
invalid role, role should be [visitor, client, manager, admin]

2021-01-12 05:55 UTC, harerakalex requested changes
Great job, however, consider the feedback I just put on this PR. in case we don't have `.gitignore` file kindly create it and put into it all files and folders that are supposed to be ignored.

2021-01-12 05:55 UTC, harerakalex commented on .nyc_output/processinfo/ba3de0ff-c050-45d0-bc69-d411000040c1.json
> +{"parent":null,"pid":9700,"argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\this PC\\Desktop\\Kitech_backend\\node_modules\\mocha\\bin\\mocha","--exit","--require","@babel/register","--requir
Better ignore this folder of `.nyc_output`

2021-01-12 05:55 UTC, harerakalex commented on coverage/lcov-report/index.html
> +
And also ignore this one `coverage` folder

2021-01-12 05:56 UTC, harerakalex commented
I think this the feature, not the chore, kindly rename the title of this PR to indicate that is a feature.

2021-01-12 08:53 UTC, truestbyheart requested changes
Please review all the comments I left, if there is any issue reach out to me

2021-01-12 08:53 UTC, truestbyheart commented on src/database/model/user.model.js
> +    required: [true, 'fullname is required, please try again'],
Please use ''full name is required' instead of ''full name is required, please try again'

2021-01-12 08:53 UTC, truestbyheart commented on src/modules/account/account.controller.js
> +                message: 'Invalid role, role should be array [visitor, client, manager, admin]',
use joi validation for this

2021-01-12 08:53 UTC, truestbyheart commented on src/modules/account/account.middleware.js
> +import Joi from '@hapi/joi';
switch to joi

2021-01-12 08:53 UTC, truestbyheart commented on src/modules/account/account.middleware.js
> +const joiMessageFunction = (error, req, res, next) => {
Please create a single function that will run all validation for the whole app, the function should be
1. should be a middleware that can be placed on any route
2. should receive a joi schema and return error once validation is done
3. should move on if there is no error

2021-01-12 08:53 UTC, truestbyheart commented on src/modules/account/account.test.js
> +  // it('users should be able to create an account with correct body', (done) => {
Please remove commented code if it no longer useful

2021-01-12 08:54 UTC, truestbyheart commented
And please ignore the coverage and nyc output files

2021-01-12 20:41 UTC, key-joshua commented on src/database/model/user.model.js
> +      'fixed phone number address is required, please try again',
I am done with this feedback @fridolinho

2021-01-12 20:42 UTC, key-joshua commented on src/modules/account/account.controller.js
> +                message: 'Invalid role, role should be array [visitor, client, manager, admin]',
I am done with this feedback @fridolinho and @truestbyheart.

2021-01-12 20:43 UTC, key-joshua commented on .nyc_output/processinfo/ba3de0ff-c050-45d0-bc69-d411000040c1.json
> +{"parent":null,"pid":9700,"argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\this PC\\Desktop\\Kitech_backend\\node_modules\\mocha\\bin\\mocha","--exit","--require","@babel/register","--requir
I am done with your feedback @harerakalex.

2021-01-12 20:44 UTC, key-joshua commented on coverage/lcov-report/index.html
> +
> And also ignore this one `coverage` folder

@harerakalex, I am done with this feedback as well.

2021-01-12 20:48 UTC, key-joshua commented on src/modules/account/account.middleware.js
> +import Joi from '@hapi/joi';
@truestbyheart, I am just done with this feedback as well.

2021-01-12 20:49 UTC, key-joshua commented on src/modules/account/account.test.js
> +  // it('users should be able to create an account with correct body', (done) => {
@truestbyheart, I am just done with this feedback.

2021-01-12 20:50 UTC, key-joshua commented on src/database/model/user.model.js
> +    required: [true, 'fullname is required, please try again'],
> Please use ''full name is required' instead of ''full name is required, please try again'

@truestbyheart, I am just done with this feedback.

2021-01-12 20:54 UTC, key-joshua commented on src/modules/account/account.middleware.js
> +const joiMessageFunction = (error, req, res, next) => {
> Please create a single function that will run all validation for the whole app, the function should be
> 
> 1. should be a middleware that can be placed on any route
> 2. should receive a joi schema and return error once validation is done
> 3. should move on if there is no error

@truestbyheart, Kind of difficult feedback - but I am just really done with it as well.

2021-01-12 20:55 UTC, key-joshua commented
> I think this the feature, not the chore, kindly rename the title of this PR to indicate that is a feature.

@harerakalex, I am just done with your feedback.

2021-01-12 20:56 UTC, key-joshua commented
> And please ignore the coverage and nyc output files

@truestbyheart, I am just done with your feedback.

2021-01-12 20:59 UTC, key-joshua commented
> Please review all the comments I left, if there is any issue reach out to me

@truestbyheart, I have gone through all the feedback you left on my PR and now I am just done to respond to your feedback today.

2021-01-13 04:17 UTC, harerakalex requested changes
Kindly consider the following feedback

2021-01-13 04:17 UTC, harerakalex commented on src/modules/account/account.controller.js
> +        return res.status(200).json({
Can you please create a generic function for sending response? and if you defined constant remember to use them always, for instance, you have constant `ok` but here you are still writing `200` as status.

2021-01-13 04:17 UTC, harerakalex commented on src/modules/account/account.middleware.js
> +  const { error } = accountSchema.validate(req.body, {
I was wondering also if you can create a generic function to handle errors.

2021-01-13 04:17 UTC, harerakalex commented on .gitignore
> +coverage/
Kindly ignore package-lock.json too.

2021-01-13 06:26 UTC, harerakalex requested changes

2021-01-13 06:26 UTC, harerakalex commented on src/modules/account/account.test.js
> +  it('users should not be able to create an account without wrong body', (done) => {
Well tested, however, You should also test all possible output this endpoint can give, for example, test when `successfully created an account`.

2021-01-13 06:56 UTC, key-joshua commented on src/modules/account/account.middleware.js
> +  const { error } = accountSchema.validate(req.body, {
The one you are saying, it is the one I did before but @truestbyheart - he just told me to use one function to validate with Joi. So, this is what I implemented/completed now.

## Previous Feedback
![reference](https://user-images.githubusercontent.com/38179232/104416630-cbe4b080-557c-11eb-867a-da9e3948a747.PNG)

2021-01-13 06:57 UTC, key-joshua commented on src/modules/account/account.controller.js
> +        return res.status(200).json({
@harerakalex, I am just done with this feedback.

2021-01-13 07:29 UTC, key-joshua commented on src/modules/account/account.test.js
> +  it('users should not be able to create an account without wrong body', (done) => {
@harerakalex, I am just done with this feedback.

![test](https://user-images.githubusercontent.com/38179232/104419871-c63d9980-5581-11eb-8c16-21f9851d2ee9.PNG)

2021-01-13 07:43 UTC, key-joshua commented
> Hello @key-joshua Good job so far, however I didn't see the successful test case.

@fridolinho, Here You can see all my tests are passing.

https://app.circleci.com/pipelines/github/KitechRW/Kitech_backend/61/workflows/6a1dfc92-bdbe-4a7f-be89-6bb900e0021f/jobs/70/steps

![Test Done](https://user-images.githubusercontent.com/38179232/104421226-c048b800-5583-11eb-91c7-6ea7f3a34dbb.PNG)

![Test Done Already](https://user-images.githubusercontent.com/38179232/104421241-c474d580-5583-11eb-9c28-24a0a0e537ff.PNG)

2021-01-13 08:03 UTC, harerakalex commented on src/modules/account/account.middleware.js
> +  const { error } = accountSchema.validate(req.body, {
Well, where is it? @key-joshua

2021-01-13 08:11 UTC, key-joshua commented on src/modules/account/account.middleware.js
> +  const { error } = accountSchema.validate(req.body, {
There you can see - he just told me to create one function that will run all validation. So for me, I just create a single function called validateUser and I place it in the route where can validate a request.

2021-01-13 08:12 UTC, harerakalex commented on src/modules/account/account.test.js
> +  it('users should not be able to create an account without wrong body', (done) => {
Well tested, I was wondering if you can go deep and test the specific message that you send in the response.

2021-01-13 08:13 UTC, harerakalex commented on src/modules/account/account.middleware.js
> +  const { error } = accountSchema.validate(req.body, {
Which one did you create? @key-joshua

2021-01-13 08:25 UTC, key-joshua commented on src/modules/account/account.middleware.js
> +  const { error } = accountSchema.validate(req.body, {
**`validateUser()`**

2021-01-13 09:28 UTC, harerakalex requested changes
One more feedback, kindly document every function with `JSDOC`.

2021-01-13 10:13 UTC, key-joshua commented on src/modules/account/account.middleware.js
> +  const { error } = accountSchema.validate(req.body, {
@harerakalex, I am done with this feedback.

2021-01-13 10:14 UTC, key-joshua commented on src/modules/account/account.test.js
> +  it('users should not be able to create an account without wrong body', (done) => {
@harerakalex, I am just done with this feedback as well.

2021-01-13 18:34 UTC, truestbyheart requested changes

2021-01-13 18:34 UTC, truestbyheart commented on src/modules/account/account.middleware.js
> +  const { error } = accountSchema.validate(req.body, {
no @key-joshua what I meant is you create a function that receives schemas to validate and if it passes it moves on if it fails it returns an error with a list of all errors.

2021-01-13 18:34 UTC, truestbyheart commented on src/modules/index.js
> +indexRouter.use('/create-user-account', accountRouter);
should use `/register` instead of this name

2021-01-13 21:29 UTC, key-joshua commented on src/modules/account/account.middleware.js
> +  const { error } = accountSchema.validate(req.body, {
@truestbyheart, I am Done.

2021-01-13 21:30 UTC, key-joshua commented on src/modules/index.js
> +indexRouter.use('/create-user-account', accountRouter);
@truestbyheart, I am Done

2021-01-13 21:35 UTC, key-joshua commented
> One more feedback, kindly document every function with `JSDOC`.

@harerakalex, Done

2021-01-14 06:44 UTC, fridolinho commented
![](https://github.trello.services/images/mini-trello-icon.png) [The user should be able to create an account.](https://trello.com/c/rYY47tdU/14-the-user-should-be-able-to-create-an-account)

2021-01-14 06:47 UTC, key-joshua commented
> ![](https://camo.githubusercontent.com/208d50cabd9d101500fe5dd548265dcfa00e017e397395692a173e7116c1094a/68747470733a2f2f6769746875622e7472656c6c6f2e73657276696365732f696d616765732f6d696e692d7472656c6c6f2d69636f6e2e706e67) [The user should be able to create an account.](https://trello.com/c/rYY47tdU/14-the-user-should-be-able-to-create-an-account)

2021-01-18 09:57 UTC, harerakalex approved these changes

2021-01-18 14:42 UTC, raymond42 commented on src/modules/account/account.helper.js
> +const UserSchema = require('../../database/model/user.model');
couldn't it be much better if we use es6 syntax for all the imports?

2021-01-18 14:44 UTC, raymond42 commented on src/modules/account/account.helper.js
> +module.exports = AccountHelpers;
same here and for all the exports, if we use es6 syntax it could be much better

2021-01-18 14:55 UTC, raymond42 commented on src/database/model/user.model.js
> +  email: {
can we have a unique property on the email field? it will avoid duplications for the user

2021-01-18 14:57 UTC, raymond42 requested changes
Good work @key-joshua. My only concern is how we can avoid the same user to be created twice, and also attend to other comments left. otherwise good job

2021-01-19 06:58 UTC, raymond42 commented on src/server.js
> +  const mongod = new MongoMemoryServer();
why are we using `MongoMemoryServer` yet we have our db configuration already with mongoose in config file? This might lead to future loss of data. you don't need to make any change to this file, you can just add your `MONGODB_URL` in `.env file` and connect to that database instead of connecting using `MongoMemoryServer`

2021-01-20 05:46 UTC, fridolinho commented on src/server.js
> +  const mongod = new MongoMemoryServer();
Good, I was going to ask for this as well?? @key-joshua Thank you @raymond42

2021-01-20 10:09 UTC, key-joshua commented on src/modules/account/account.helper.js
> +module.exports = AccountHelpers;
@raymond42  I am Done with this feedback

2021-01-20 10:09 UTC, key-joshua commented on src/modules/account/account.helper.js
> +const UserSchema = require('../../database/model/user.model');
@raymond42  I am Done with this feedback

2021-01-20 10:09 UTC, key-joshua commented on src/database/model/user.model.js
> +  email: {
@raymond42  I am Done with this feedback

2021-01-20 10:10 UTC, key-joshua commented on src/server.js
> +  const mongod = new MongoMemoryServer();
@raymond42, @fridolinho  I am Done with this feedback

2021-01-20 10:25 UTC, fridolinho approved these changes

2021-01-20 10:25 UTC, merged