edit user profile
KitechRW/Kitech_backend pull request #9
Opened 2021-01-13 22:31 UTC by patrickngabo

#### what does this PR do?
 - Edit user profile
#### Description of task to be completed
 - User shoud be able to edit his profile
#### How should this be manually tested
 To test this endpoint you need to use postman and type: /api/v1/account/:id
#### Any background context you want to provide

#### What are the relevant trello story link

#### Screenshots (if appropriate)

#### Questions:

2021-01-14 08:23 UTC, fridolinho commented
![](https://github.trello.services/images/mini-trello-icon.png) [Users should be able to update their profile details.](https://trello.com/c/VCx3tNHS/17-users-should-be-able-to-update-their-profile-details)

2021-01-25 07:59 UTC, truestbyheart requested changes
Great work just a feddback or two and we are good to go

2021-01-25 07:59 UTC, truestbyheart commented on src/modules/account/__tests__/account.test.js
> +import { _ } from 'lodash';
Please just import what u need like `{ omit }` loading the whole library is too much

2021-01-25 07:59 UTC, truestbyheart commented on src/modules/account/account.controller.js
> +        message: 'something went wrong',
Please write a more descriptive error message, like `Fail to update profile`

2021-01-25 13:37 UTC, harerakalex approved these changes
LGTM @patrickngabo

2021-01-25 20:57 UTC, luc-tuyishime commented
Can you add a screenshot in the PR description ?

2021-01-26 09:56 UTC, patrickngabo commented
> Can you add a screenshot in the PR description ?

Screenshot added

2021-01-26 09:57 UTC, patrickngabo commented on src/modules/account/__tests__/account.test.js
> +import { _ } from 'lodash';
Import fixed.

2021-01-26 09:58 UTC, patrickngabo commented on src/modules/account/account.controller.js
> +        message: 'something went wrong',
error message fixed

2021-01-28 09:26 UTC, merged